// ─────────────────────────────────────────────────────────────────────────────
// CSV export.
//
// Pure string functions, no DOM and no React — same rule as lib/mortgage.ts
// (technical brief §7). The Blob and the anchor click live in the component
// that calls this, so the schedule can also be generated by the embeddable
// widget later without dragging a browser API along with it.
// ─────────────────────────────────────────────────────────────────────────────

import type { PayoffRow } from "@/lib/mortgage";

/**
 * Quotes a field only when it needs it, per RFC 4180.
 *
 * Exported August 18, 2026. It was private, and the 15-versus-30 calculator's
 * export was joining its own rows with a bare `join(",")` while carrying eight
 * labels with commas inside them, which shifted every value on those rows into
 * the wrong column. The other calculators had only avoided it by happening to
 * use comma-free labels. A second copy of an escaper would have been the
 * defect (§0.13), so the one that already existed is now shared.
 */
export function csvCell(value: string | number): string {
  return cell(value);
}

function cell(value: string | number): string {
  const s = String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function row(values: (string | number)[]): string {
  return values.map(cell).join(",");
}

/** Two decimal places, no thousands separators — spreadsheets parse this. */
function money(n: number): string {
  return n.toFixed(2);
}

export type ScheduleMeta = {
  /** e.g. "Payoff with extra payments" */
  tool: string;
  loanAmount: number;
  annualRatePct: number;
  termMonths: number;
  extraMonthly: number;
  /**
   * A plain-English description of the whole extra-payment plan, when there is
   * more to it than one monthly amount — a lump sum, a yearly extra, a
   * biweekly schedule, a delayed start.
   *
   * Optional, and it supersedes `extraMonthly` in the preamble when present.
   * Added August 12, 2026 with the payoff plan rebuild: a downloaded schedule
   * whose preamble says "plus $250 extra each month" when the run also
   * included a $10,000 lump sum is worse than no preamble at all, because it
   * looks authoritative and is wrong.
   */
  planNote?: string;
};

/**
 * The full month-by-month schedule as CSV.
 *
 * A three-line preamble carries the inputs before the table starts. This is a
 * deliberate trade: it makes the file marginally less convenient for a script
 * to parse, and much more useful to the person who actually downloads it —
 * a schedule with no record of the rate it came from is worthless a month
 * later, and nobody writes the rate down.
 */
export function scheduleToCsv(
  schedule: PayoffRow[],
  meta: ScheduleMeta,
): string {
  const years = (meta.termMonths / 12).toFixed(
    meta.termMonths % 12 === 0 ? 0 : 2,
  );

  const lines: string[] = [
    row([`Plain Loan Math — ${meta.tool}`]),
    row([
      `Loan ${money(meta.loanAmount)} at ${meta.annualRatePct}% over ${years} years` +
        (meta.planNote
          ? `, ${meta.planNote}`
          : meta.extraMonthly > 0
            ? `, plus ${money(meta.extraMonthly)} extra each month`
            : ", no extra payment"),
    ]),
    row([
      "Estimates only. Not financial advice, and not a loan offer. plainloanmath.com",
    ]),
    "",
    row([
      "Month",
      "Payment",
      "Interest",
      "Principal",
      "Extra",
      "Balance",
    ]),
  ];

  for (const r of schedule) {
    lines.push(
      row([
        r.month,
        money(r.interest + r.principal + r.extra),
        money(r.interest),
        money(r.principal),
        money(r.extra),
        money(r.balance),
      ]),
    );
  }

  // Trailing newline: some spreadsheet importers drop the final row without it.
  return lines.join("\r\n") + "\r\n";
}

/**
 * The payment breakdown as CSV — one row per component of the monthly payment.
 * Used by the payment calculator, which answers "what is my payment made of"
 * rather than "how does the balance run down".
 */
export function breakdownToCsv(
  parts: { label: string; value: number }[],
  meta: { homePrice: number; downPayment: number; annualRatePct: number; termMonths: number },
): string {
  const total = parts.reduce((sum, p) => sum + p.value, 0);
  const years = (meta.termMonths / 12).toFixed(
    meta.termMonths % 12 === 0 ? 0 : 2,
  );

  const lines: string[] = [
    row(["Plain Loan Math — monthly payment breakdown"]),
    row([
      `${money(meta.homePrice)} home, ${money(meta.downPayment)} down, ` +
        `${meta.annualRatePct}% over ${years} years`,
    ]),
    row([
      "Estimates only. Not financial advice, and not a loan offer. plainloanmath.com",
    ]),
    "",
    row(["Component", "Monthly amount", "Share of payment"]),
  ];

  for (const p of parts) {
    const share = total > 0 ? ((p.value / total) * 100).toFixed(1) : "0.0";
    lines.push(row([p.label, money(p.value), `${share}%`]));
  }

  lines.push(row(["Total", money(total), "100.0%"]));

  return lines.join("\r\n") + "\r\n";
}
